distribution_code_name: "ibus-rime"
distribution_name: Rime
distribution_version: 1.3
install_time: "Wed Oct 17 15:16:56 2018"
installation_id: "0d90e8fd-639f-4407-8fdd-d537bd562bce"
rime_version: 1.3.1
update_time: "Sat Oct 20 14:33:45 2018"