distribution_code_name: "fcitx-rime"
distribution_name: Rime
distribution_version: 0.2.3
install_time: "Fri Nov 29 23:36:51 2019"
installation_id: "9c39774f-c7eb-491a-966f-00c97bd7fb19"
rime_version: 1.5.3