distribution_code_name: "fcitx-rime"
distribution_name: Rime
distribution_version: 0.2.3
install_time: "Thu May 16 19:55:27 2019"
installation_id: "30a4ff6d-cc47-4cc3-9379-6ec245079f24"
rime_version: 1.5.3
update_time: "Fri Aug 16 10:59:25 2019"