distribution_code_name: "fcitx-rime"
distribution_name: Rime
distribution_version: 0.2.3
install_time: "Tue Mar 17 15:27:55 2020"
installation_id: "47cf925e-635b-4d0c-a876-31e53639bd99"
rime_version: 1.5.3
sync_dir: "/Users/cycleke/Nutstore Files/Rime"
update_time: "Tue May 26 09:02:46 2020"