distribution_code_name: "fcitx-rime"
distribution_name: Rime
distribution_version: 0.2.3
install_time: "Wed Oct 17 15:16:56 2018"
installation_id: "0d90e8fd-639f-4407-8fdd-d537bd562bce"
rime_version: 1.3.1
update_time: "Sat Oct 20 22:21:00 2018"