var:
  last_build_time: 1591003238
  previously_selected_schema: double_pinyin_flypy
  schema_access_time:
    double_pinyin_flypy: 1589807571
    luna_pinyin_fluency: 1548337106
    luna_pinyin_simp: 1589648156